name: neouuid
description: Fast and idiomatic UUIDs (Universally Unique Identifiers) in Dart.
version: 0.0.0
homepage: https://github.com/neo-dart/neouuid

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  benchmark_harness: ^2.2.0
  coverage: ^1.5.0
  neodart: ^0.1.1
  test: ^1.21.4
